### ISSUE TITLE
Update changelog github action needs to update _index.md with the url to latest version

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/grafana-github-actions#13]

**Comment by tolzhabayev** [comment]
@ying-jeanne could you add more details as to [which](https://github.com/search?q=repo%3Agrafana%2Fgrafana+filename%3A_index.md&type=Code&ref=advsearch&l=&l=) _index.md file should be updated?

**Comment by tolzhabayev** [comment]
I guess you mean [this one](https://github.com/grafana/grafana/blob/main/docs/sources/release-notes/_index.md) right?
