### ISSUE TITLE
Support command/action for automatically assigning GitHub project to issue/PR

### ISSUE THREAD

**Issue by marefr** [grafana/grafana-github-actions#29]
Why:
More and more teams are using GitHub projects in their day-to-day work and currently it's a completely manual task to assign GitHub projects to issues/PRs. Could simplify a lot of things if issue/PR could be automatically assigned to GitHub project based on certain label assigned for example.

Example usage:
Based on the existing [issue commands](https://github.com/grafana/grafana/blob/main/.github/commands.json) and [PR commands](https://github.com/grafana/grafana/blob/main/.github/pr-commands.json) in the Grafana repository something like the following would be nice:

Org project:
Based on certain label assigned add issue/PR to project.

```json
{
    "type": "label",
    "name": "area/backend",
    "action": "addToProject",
    "addToProject": {
        "url": "https://github.com/orgs/grafana/projects/27",
        "column": "To do"
    }
}
``` 

Repository project:
Based on certain label assigned add issue/PR to project.

```json
{
    "type": "label",
    "name": "area/backend",
    "action": "addToProject",
    "addToProject": {
        "url": "https://github.com/grafana/grafana/projects/15",
        "column": "Inbox"
    }
}
```

More information:
GitHub rest api in regards to projects seems very limited/hard to use to achieve this task. But seems like the graphql api might be easier to at least figure out the input parameters needed to add/move an issue/PR to a GitHub project. The project below are using the rest api and seems to do a lot of request to figure things out.

Some inspiration from https://github.com/marketplace/actions/automate-projects and https://github.com/takanabe/github-actions-automate-projects

**Comment by tolzhabayev** [comment]
@marefr I will try my luck trying to automate it
