### ISSUE TITLE
Bump version action should re-generate the yarn.lock file

### ISSUE THREAD

**Issue by marefr** [grafana/grafana-github-actions#37]
When releasing 8.3.0-beta1 and 8.3.0-beta2 we had to manually run `yarn` to re-generate the yarn.lock file and commit it, see [commit](https://github.com/grafana/grafana/pull/42297/commits/1234ecb370796d7e4191ceb22f6345fdd596e40f) and [PR](https://github.com/grafana/grafana/pull/42297).

If we run yarn when bumping version for older Grafana versions, like v8.2.6/v8.2.x branch - would that cause any harm?

**Comment by zoltanbedi** [comment]
It shouldn't cause harm. The lock file should always be in the same state in older branches so running yarn install shouldn't create yarn.lock changes.
