### ISSUE TITLE
PR Checks: Status sometimes overridden by action started before another action

### ISSUE THREAD

**Issue by marefr** [grafana/grafana-github-actions#76]
Status sometimes overridden by action started before another action resulting in status showing as "failed" even though it should be "successful".

**Example:**
Pull request opened action triggered below run and checking the timestamps it got the check result `Milestone not set` at Tue, 08 Feb 2022 08:22:21 GMT:
https://github.com/grafana/grafana-enterprise/runs/5105886551?check_suite_focus=true

Pull request milestoned action triggered below run and checking the timestamps it got the check result `Milestone set` at Tue, 08 Feb 2022 08:22:20 GMT:
https://github.com/grafana/grafana-enterprise/runs/5105886663?check_suite_focus=true

**Comment by tolzhabayev** [comment]
Will try to see if specifying `concurrency` parameter helps: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
